Morfusee/Firestore-ERD-Plus

.gitignore
documentation/introduction.md
package-lock.json
package.json
src/App.tsx
src/components/TopMiddleBar.tsx
src/components/modals/CodeGenModal.tsx
src/components/modals/SettingsModal.tsx
src/data/repo/useEditorRepo.ts
src/pages/editor/index.tsx

- Code gen modal with syntax highlighting
- Initial JSDoc descriptors
- Moved all modals to the modal folder
- Installed react-syntax-highlighter library
- Initial documentation directory and gitignore

FEAT: Implemented Code Gen Modal and other changes

---

src/App.tsx
src/components/TopRightBar.tsx
src/components/modals/ManageAccountModal.tsx
src/pages/FirestoreERD.tsx

- Implemented TopRight action bar
- Implemented Version History popover
- Implemented Account popover
- Initial implementation for Manage Account modal

FEAT: Implemented Version History & Account Popover

---

server/app.ts
server/controllers/settingsControllers.ts
server/models/settingsModel.ts
server/routes/settingsRoutes.ts

// TODO: switch type and use reference on the commented line after User is implemented
Settings Schema:
- user: current logged in user,
- autoSaveInterval: auto save seconds interval. Defaults to 0 sec
- canvasBackground: background pattern for thecanvas. Uses enums and defaults to "Dots"
- theme: Uses enums. Defaults to "System"
Controllers:
- getSettingsByUserId: uses user Id in the parameters to retrieve the settings
- createSettings: creates user settings
- updateSettings: updates user settings

FEAT: Implemented Settings Model, Routes, and Controller

---

src/App.tsx
src/components/TopMiddleBar.tsx
src/components/TopRightBar.tsx
src/components/modals/DownloadModal.tsx
src/components/modals/ManageAccountModal.tsx
src/components/modals/ShareModal.tsx

- Implemented Manage Account modal
- Implemented mostly Share Modal
- Implemented mostly Download Modal
- Added history button disable when no project is currently selected
- Fixed history drawer scrolling issue

FEAT: (FE) Manage Acc, Share, and Download Modal

---

package-lock.json
server/app.ts
server/controllers/userController.ts
server/middleware/userValidator.ts
server/models/userModel.ts
server/package-lock.json
server/package.json
server/routes/userRoutes.ts

This pull request introduces the following changes to the project:
- User Model: Added a model for user with fields such as username, email, displayName, and token.
- Validation Middleware: Implemented validation for user input (email, username, displayName) using express-validator to ensure correct data formats.
- User CRUD Operations: Added controller functions to handle creating, retrieving, updating, and searching users by email.
- User Routes: Defined Express routes for all CRUD operations, user search by email, and validation during user creation.

Feat: Implement user model, validation, CRUD operations, and routes

---

server/controllers/userController.ts
server/middleware/userValidator.ts

Changes:
1. updateUser Function: Added a return after the 404 response when the user is not found, preventing further execution.
2. getUserByEmail Function:  Added a return after the 400 response for invalid limit values to ensure proper flow control.
3. validate Middleware: Added a return after the 400 response for validation errors to avoid inadvertently calling next().

Fix: Ensure proper flow control in API handlers and middleware

---

server/controllers/userController.ts
server/models/userModel.ts
server/package-lock.json
server/routes/projectRoutes.ts
server/routes/userRoutes.ts

Additional Changes:
- Added middleware for cascade deletion of owned projects
- Added IUser to have intellisense

FEAT (Users): Implemented Deletion of User

---

server/app.ts
server/controllers/memberControllers.ts
server/errors/ConflictError.ts
server/errors/HTTPError.ts
server/errors/NotFoundError.ts
server/errors/ValidationError.ts
server/middleware/errorMiddleware.ts
server/middleware/memberValidator.ts
server/models/memberModel.ts
server/models/projectModel.ts
server/models/userModel.ts
server/routes/memberRoutes.ts
server/types/memberTypes.ts

- Added memberController
- Get members by project id
- Add member
- Change member role
- Remove Member
- Added memberRoutes
- Added memberTypes
- Implemented request validators for member controller
- Changed Project model to include members array
- Changed User model to include ownedProjects and sharedProjects array
- Added custom Errors and error handling middleware

FEAT (Members): Implemented CRUD and routes

---

.env.template
.gitignore
server/app.ts
server/controllers/emojiControllers.ts
server/routes/emojiRoutes.ts
server/types/emojiTypes.ts
src/App.tsx
src/components/AsyncEmojiPicker.tsx
src/components/TopLeftBar.tsx
src/components/modals/DeleteModal.tsx
src/components/modals/DrawerModal.tsx
src/types/EmojiData.ts
src/utils/useEmojiData.tsx
src/utils/useTheme.tsx

Additional Changes:
- Added .env.template and .env for having a unified variable for the server's URL
- Created a new component called AsyncEmojiPicker to asynchronously call Emojis from the backend
- Implemented proper theming for the TabsTab component
- Used Emoji Family as the 3rd Party API
- Modified Tab Panel structure
- Added Tabs
- Removed other routes
- Simplified routes for fetching by groups
- Transferred Drawer Modal to its own file

FEAT: Implemented Endpoint for Fetching of Emojis from 3rd Party and on the Frontend

---

server/app.ts
server/controllers/projectController.ts
server/middleware/responseStatusMiddleware.ts
server/middleware/successMiddleware.ts
server/models/projectModel.ts
server/routes/projectRoutes.ts
server/success/SuccessResponse.ts
server/types/projectTypes.ts
src/components/TopLeftBar.tsx
src/components/modals/DrawerModal.tsx
src/data/api/projectsApi.ts
src/data/db/AppDB.ts
src/data/db/Project.ts
src/data/repo/useDataInitializer.ts
src/data/repo/useProjectRepo.ts
src/store/useProjectStore.ts
src/types/ProjectTypes.ts

Additional changes:
- Modified project types for backend and frontend
- Fixed type errors
- Refactored ProjectRepo and ProjectStore
- Added SuccessMiddleware 
- Added SuccessResponse

FEAT (Drawer): Implemented Creating and Fetching of Projects

---

server/controllers/projectController.ts
server/middleware/responseStatusMiddleware.ts
server/utils/isSuccessStatus.ts
src/components/TopLeftBar.tsx
src/components/icons/StatusIcon.tsx
src/components/modals/DeleteModal.tsx
src/components/modals/DrawerModal.tsx
src/data/api/projectsApi.ts
src/data/repo/useDataInitializer.ts
src/data/repo/useProjectRepo.ts
src/store/useProjectStore.ts
src/utils/successHelpers.ts

Backend Changes:
- Implemented response status middleware to ensure consistent API responses.
- Standardized success response objects across all endpoints.
Frontend Changes:
- Added optimistic UI updates.
- Refactored useProjectRepo.ts.
- Implemented full CRUD operations on the frontend, aligning them with API changes.

FEAT: Refactor server responses and improve frontend CRUD operations

---

server/controllers/settingsControllers.ts
server/models/historyModel.ts
server/models/projectModel.ts
server/models/settingsModel.ts
server/models/userModel.ts
server/utils/mongooseTransformPlugin.ts

- Updated Settings model to reference User using ObjectId.
- Applied mongooseTransformPlugin for cleaner JSON output.
- Fixed getSettingsByUserId to correctly query by user field.
- Corrected updateSettings to properly update settings based on user reference.
- Optimized cascading deletion of settings when a user is removed.
- Ensured automatic creation of user settings upon user creation.

feat: enhance settings management and fix user reference in controllers

---

package-lock.json
package.json
server/controllers/authController.ts
server/middleware/validators/authValidator.ts
server/routes/authRoutes.ts
server/types/authTypes.ts
src/App.tsx
src/components/TopRightBar.tsx
src/components/modals/DownloadModal.tsx
src/data/api/authApi.ts
src/data/api/projectsApi.ts
src/data/api/userApi.ts
src/data/repo/useAuth.tsx
src/data/repo/useDataInitializer.ts
src/data/repo/useDownloadRepo.ts
src/data/repo/useEditorRepo.ts
src/data/repo/useUserRepo.ts
src/pages/FirestoreERD.tsx
src/pages/login/index.tsx
src/pages/register/index.tsx
src/routes/ProtectedRoute.tsx
src/types/APITypes.ts
src/types/DownloadModalTypes.ts
src/utils/useAuth.tsx
vite.config.ts

Additional Changes:
- Combined register and login functions with find user by email
- Implemented registering of users
- Implemented better error handling for authApi
- Implemented better UI feedback for clicking login and register buttons
- Implemented logging out of user
- Added pending changes from another account

Feature Enhancements and Comprehensive Code Cleanup

---

package-lock.json
package.json
src/App.tsx
src/components/modals/ImageCropperModal.tsx
src/components/modals/ManageAccountModal.tsx
src/css/index.css
src/data/repo/useUserRepo.ts
src/store/useUserStore.ts

This pull request introduces the following changes:
**Dependency Updates:**
- Added react-advanced-cropper to package.json and package-lock.json.
- Updated advanced-cropper, classnames, and other related dependencies.
**New Features:**
- Added ImageCropperModal component to enable image cropping functionality for user profile images.
- Integrated the ImageCropperModal into the ManageAccountModal for profile image uploading and cropping.
**Enhancements:**
- Updated ManageAccountModal to include profile image upload, crop, and save functionalities.
- Modified useUserRepo and useUserStore to handle profile image state updates.
- Updated CSS imports to include styles for the react-advanced-cropper.

Add Image Cropping Feature and Enhance Profile Management

---

server/config/firebase.ts
server/controllers/authController.ts
src/pages/login/index.tsx
src/pages/register/index.tsx
src/utils/errorHelpers.ts

addtl changes:
- Changed error displaying mechanism to further catch errors from both the database and the firebase auth

feat: improved login and signing up mechanisms to protect auth provider

---

package-lock.json
package.json
server/middleware/compressImageMiddleware.ts
server/package-lock.json
server/package.json
server/routes/userRoutes.ts

This PR introduces an image compression middleware using the sharp library. The middleware compresses and resizes images before they are uploaded to Firebase Storage, ensuring optimized file sizes and consistent dimensions.
- Added compressImage middleware to handle image compression.
- Integrated the middleware into the /profile-picture route.

feat: add image compression middleware using sharp

---

server/controllers/authController.ts
server/controllers/emojiControllers.ts
server/middleware/validators/authValidator.ts
server/utils/getFirebaseAuthErrorMessage.ts
src/components/modals/ImageCropperModal.tsx
src/components/modals/ManageAccountModal.tsx
src/components/ui/ProfileAvatar.tsx
src/data/api/emojiApi.ts
src/data/api/userApi.ts
src/data/db/AppDB.ts
src/data/repo/useEmojiRepo.ts
src/data/repo/useUserRepo.ts
src/hooks/useEmojiData.tsx
src/layouts/TopRightBar.tsx
src/store/useUserStore.ts
src/types/APITypes.ts

This pull request includes several updates and improvements across various parts of the project:
**Authentication:**
- Fixed a bug in authController.ts by changing User.find to User.findOne for proper user retrieval.
- Improved error handling and token validation in authValidator.ts.
**Emoji Management:**
- Introduced SuccessResponse in emojiControllers.ts for better response handling.
- Enhanced error handling and response structure for fetching emojis by group.
**Profile Handling:**
- Added features to ImageCropperModal.tsx for image uploading with loading indicators and notifications.
- Created ProfileAvatar.tsx for better avatar handling and loading states.
- Updated ManageAccountModal.tsx to use ProfileAvatar and handle image loading states.
**Miscellaneous:**
- Adjusted database …

Enhancements and Bug Fixes for Authentication, Emoji Management, and Profile Handling

---

server/controllers/memberControllers.ts
server/controllers/projectController.ts
server/middleware/validators/memberValidator.ts
server/models/projectModel.ts
server/routes/memberRoutes.ts
src/components/modals/ShareModal.tsx
src/components/ui/ProfileAvatar.tsx
src/data/api/membersApi.ts
src/data/repo/useDataInitializer.ts
src/data/repo/useMemberRepo.ts
src/data/repo/useProjectRepo.ts
src/store/useMemberStore.ts
src/store/useProjectStore.ts
src/types/APITypes.ts
src/types/ProjectTypes.ts

UI
- added fields for typing in email when adding a new member
- added menu for changing project owner and removing members / leaving
API
- added a separate API, store, repo/hooks for project members
BE
- updated memberControllers to use email to add project members

FEAT: Implemented Project Sharing Displaying and Add/Remove Project Members

---

server/middleware/validators/settingsValidator.ts
server/models/settingsModel.ts
server/types/memberTypes.ts
src/App.tsx
src/components/modals/SettingsModal.tsx
src/components/modals/ShareModal.tsx
src/constants/modalConstants.ts
src/data/api/membersApi.ts
src/data/api/settingsApi.ts
src/data/repo/useDataInitializer.ts
src/data/repo/useSettingsRepo.ts
src/hooks/useTheme.tsx
src/layouts/TopLeftBar.tsx
src/pages/editor/index.tsx
src/routes/AppRoutes.tsx
src/store/useSettingsStore.ts

- Fixed a missing semicolon in `settingsValidator.ts`.  
- Removed `"System"` from the theme options in `settingsValidator.ts` and `settingsModel.ts`.  
- Changed the default theme to `"Light"`.  
- Added semicolons to `memberTypes.ts`.  
- Included `email` field in `MemberBody` interface.  
1. Reorganized imports in `App.tsx`.  
2. Combined modal imports into `modalConstants.ts`.  
3. Updated routing to use `AppRoutes`.  
1. Refactored `SettingsModal.tsx` with new settings repository hooks.  
2. Simplified `ShareModal.tsx` props and state management.

Settings Validation, Model Updates, Member Types Enhancements, and App Component Refactoring  

---

src/components/modals/ShareModal.tsx

addtl changes:
- merged two useEffects w the same dependency into one

fix: typescript errors causing builds to fail

---

.gitignore
server/compose.prod.yml
server/config/passport.ts
server/traefik-config/dynamic.yml
server/traefik-config/static.yml
server/utils/usernameGenerator.ts
src/layouts/TopLeftBar.tsx
src/pages/login/index.tsx
src/pages/register/index.tsx

- **Added middleware** to block forceful browsing on sensitive files.  
- **Implemented a Reddit-like username generator** for Google OAuth authentication.  
- **Moved Traefik configuration** into static and dynamic config files.  
- **Added `.env.prod`** to `.gitignore` for better security.  
- **Updated `.gitignore`** to include `server/traefik-logs` and `letsencrypt` folder.  
- **Fixed missing or invalid required fields** displaying as errors instead of warnings.  
- **Updated Profile page UI** by temporarily removing a duplicate button.  
- **Enhanced exception handling** in authentication and profile views.  
- **Added documentation** for `compose-prod.yml`.

Traefik Configuration, Middleware Security, OAuth Username Generation, and Misc Updates  

---

src/components/modals/ImageCropperModal.tsx
src/components/ui/CustomNotification.tsx
src/data/repo/useCodeGenRepo.ts
src/layouts/TopLeftBar.tsx
src/layouts/TopMiddleBar.tsx
src/pages/editor/nodes/TableNode.tsx

- **Created `CustomNotification` wrapper** for a centralized notification system.  
- **Added `hasInvalidFields`** helper to check for empty fields in forms.  
- **Implemented clear UI hints** for missing fields to improve user guidance.  
- **Implemented strict modal opening behavior** for `TopMiddleBar` layout.  
- **Refactored notification logic** to use `CustomNotification` for consistency.

Fix Table Node Bug & Enhance Notification System

---

package-lock.json
package.json
server/controllers/memberControllers.ts
server/middleware/validators/memberRoleValidator.ts
server/middleware/validators/memberValidator.ts
server/models/projectModel.ts
server/package-lock.json
server/routes/memberRoutes.ts
server/tests/member.test.ts
server/types/memberTypes.ts
src/App.tsx
src/components/modals/ShareModal.tsx
src/data/api/membersApi.ts
src/data/repo/useDataInitializer.ts
src/data/repo/useEditorRepo.ts
src/data/repo/useMemberRepo.ts
src/data/repo/useProjectRepo.ts
src/layouts/TopLeftBar.tsx
src/pages/editor/index.tsx
src/pages/editor/nodes/TableNode.tsx
src/store/useMemberStore.ts
src/store/useProjectStore.ts
src/store/useUserStore.ts
src/types/APITypes.ts
src/types/ProjectTypes.ts

- Added right click context menu for Tables
- Improved role access for Frontend
- Implemented functionality for General Access option
- Other changes to role/member

FEAT: Context Menu and RBAC

---

package-lock.json
package.json
src/data/repo/useDataInitializer.ts
src/data/repo/useHistoryRepo.ts
src/pages/editor/nodes/NoteNode.tsx
src/pages/editor/nodes/TableNode.tsx

- **Fixed project history inheritance issue** where a newly created project retained the history of a previously selected project.  
- **Resolved throttled/pending changes transferring across projects**, ensuring clean state transitions.  
- **Introduced lodash** for throttling user input.  
- **Implemented cleanup functions** to properly cancel throttled text input, preventing unintended history updates.

FIX: Prevent History & Throttled Changes from Carrying Over Between Projects  
